apiVersion: v1
kind: Pod
metadata:
  name: systester1
spec:
  containers:
  - name: systester1
    image: ubuntu:20.04
    command: [ "bin/bash", "-c", "--"]
    args:
    - apt update && apt upgrade -y && apt install -y git vim ssh
    volumeMounts:
    - name: shared-data
      mountPath: /
  volumes:
  - name: shared-data
    hostPath:
      path: /root/syscaller/
      type: DirectoryOrCreate
