apiVersion: v1
kind: Pod
metadata:
  name: systester1
spec:
  containers:
  - name: systester1
    image: ubuntu:20.04
    command: ["/bin/bash", "-c"]
    args:
    - apt update && apt -y upgrade && while true; do sleep 3600; done
    volumeMounts:
    - name: ftrace
      mountPath: /data/shared
    - name : syscaller
      mountPath: /program
  volumes:
  - name : ftrace
    hostPath:
      path: /sys/kernel/debug/
      type: Directory
  - name : syscaller
    hostPath:
      path: /home/kw1
      type : Directory
      